export const FILTER = "FILTER";
export const SORT = "SORT";
export const ADD_TO_CART = "ADD_TO_CART";
export const DELETE_PRODUCT_IN_CART = "DELETE_PRODUCT_IN_CART";
export const UPDATE_PRODUCT_IN_CART = "UPDATE_PRODUCT_IN_CART";
export const CHANGE_QUANTITY_IN_CART = "CHANGE_QUANTITY_IN_CART";